// This file will be auto-generated by `supabase gen types typescript`
// For now, use a placeholder to unblock development

export type Database = {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
};
